sudo: required
services:
  - docker

before_install:
  - docker build -t docker-test -f Dockerfile.dev .

script:
  - docker run docker-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-test'
  env: 'DockerTest-env'
  bucket_name: 'elasticbeanstalk-us-east-2-985686644602'
  bucket_path: 'docker-test'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
